#
# ThingsBoard, Inc. ("COMPANY") CONFIDENTIAL
#
# Copyright Â© 2016-2025 ThingsBoard, Inc. All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains
# the property of ThingsBoard, Inc. and its suppliers,
# if any.  The intellectual and technical concepts contained
# herein are proprietary to ThingsBoard, Inc.
# and its suppliers and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
#
# Dissemination of this information or reproduction of this material is strictly forbidden
# unless prior written permission is obtained from COMPANY.
#
# Access to the source code contained herein is hereby forbidden to anyone except current COMPANY employees,
# managers or contractors who have executed Confidentiality and Non-disclosure agreements
# explicitly covering such access.
#
# The copyright notice above does not evidence any actual or intended publication
# or disclosure  of  this source code, which includes
# information that is confidential and/or proprietary, and is a trade secret, of  COMPANY.
# ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC  PERFORMANCE,
# OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS  SOURCE CODE  WITHOUT
# THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED,
# AND IN VIOLATION OF APPLICABLE LAWS AND INTERNATIONAL TREATIES.
# THE RECEIPT OR POSSESSION OF THIS SOURCE CODE AND/OR RELATED INFORMATION
# DOES NOT CONVEY OR IMPLY ANY RIGHTS TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS,
# OR TO MANUFACTURE, USE, OR SELL ANYTHING THAT IT  MAY DESCRIBE, IN WHOLE OR IN PART.
#

services:
  postgres:
    restart: always
    container_name: "${POSTGRES_NAME}"
    image: "postgres:17"
    ports:
      - "5432"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "5"
    environment:
      POSTGRES_DB: thingsboard_mqtt_broker
      POSTGRES_PASSWORD: postgres
    volumes:
      - tbmq-postgres-data:/var/lib/postgresql/data
  kafka:
    restart: always
    container_name: "${KAFKA_NAME}"
    image: "apache/kafka:4.0.0"
    ports:
      - "9092"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "5"
    env_file:
      - kafka.env
    volumes:
      - tbmq-kafka-data:/var/lib/kafka/data
      - tbmq-kafka-secrets:/etc/kafka/secrets
      - tbmq-kafka-config:/mnt/shared/config
  tbmq1:
    restart: always
    container_name: "${TBMQ_1_NAME}"
    image: "${DOCKER_REPO}/${DOCKER_NAME}:${TBMQ_VERSION}"
    ports:
      - "1883"
      - "8083"
      - "8084"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "30"
    environment:
      TB_SERVICE_ID: tbmq1
      #JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tbmq.env
    volumes:
      - tbmq-config:/config
      - tbmq1-logs:/var/log/thingsboard-mqtt-broker
    #      - PATH_TO_CERTS:/config/certificates
    depends_on:
      - postgres
      - kafka
  tbmq2:
    restart: always
    container_name: "${TBMQ_2_NAME}"
    image: "${DOCKER_REPO}/${DOCKER_NAME}:${TBMQ_VERSION}"
    ports:
      - "1883"
      - "8083"
      - "8084"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "30"
    environment:
      TB_SERVICE_ID: tbmq2
      #JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tbmq.env
    volumes:
      - tbmq-config:/config
      - tbmq2-logs:/var/log/thingsboard-mqtt-broker
    #      - PATH_TO_CERTS:/config/certificates
    depends_on:
      - postgres
      - kafka
  tbmq-integration-executor1:
    restart: always
    container_name: "${TBMQ_IE_1_NAME}"
    image: "${DOCKER_REPO}/${TBMQ_IE_DOCKER_NAME}:${TBMQ_VERSION}"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "30"
    environment:
      TB_SERVICE_ID: tbmq-ie1
      #JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tbmq-integration-executor.env
    volumes:
      - tbmq-ie-config:/config
      - tbmq-ie1-logs:/var/log/tbmq-integration-executor
    depends_on:
      - kafka
      - tbmq1
      - tbmq2
  tbmq-integration-executor2:
    restart: always
    container_name: "${TBMQ_IE_2_NAME}"
    image: "${DOCKER_REPO}/${TBMQ_IE_DOCKER_NAME}:${TBMQ_VERSION}"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "30"
    environment:
      TB_SERVICE_ID: tbmq-ie2
      #JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tbmq-integration-executor.env
    volumes:
      - tbmq-ie-config:/config
      - tbmq-ie2-logs:/var/log/tbmq-integration-executor
    depends_on:
      - kafka
      - tbmq1
      - tbmq2
  haproxy:
    restart: always
    container_name: "${LOAD_BALANCER_NAME}"
    image: thingsboard/haproxy-certbot:2.2.33-alpine
    volumes:
      - tbmq-haproxy-config:/config
      - tbmq-haproxy-letsencrypt:/etc/letsencrypt
      - tbmq-haproxy-certs-d:/usr/local/etc/haproxy/certs.d
    ports:
      - "80:80"
      - "443:443"
      - "1883:1883"
      - "8084:8084"
      - "8883:8883"
      - "8085:8085"
    cap_add:
      - NET_ADMIN
    environment:
      HTTP_PORT: 80
      HTTPS_PORT: 443
      MQTT_PORT: 1883
      MQTT_WS_PORT: 8084
      MQTTS_PORT: 8883
      MQTT_WSS_PORT: 8085
      FORCE_HTTPS_REDIRECT: "false"
    links:
      - tbmq1
      - tbmq2

volumes:
  tbmq-postgres-data:
    external: true
  tbmq-kafka-data:
    external: true
  tbmq-kafka-secrets:
    external: true
  tbmq-kafka-config:
    external: true
  tbmq1-logs:
    external: true
  tbmq2-logs:
    external: true
  tbmq-config:
    external: true
  tbmq-haproxy-config:
    external: true
  tbmq-haproxy-letsencrypt:
    external: true
  tbmq-haproxy-certs-d:
    external: true
  tbmq-ie1-logs:
    external: true
  tbmq-ie2-logs:
    external: true
  tbmq-ie-config:
    external: true
